### PR TITLE
fix: Update Input Edit Modal to use new styles and created new StoryBook

### LINKED ISSUE #1469: All Modals require visual upgrades
As mentioned in [this post](https://cultureamp.slack.com/archives/CETLTFG9G/p1619056402029500), there have been a host of improvements made to our `Confirmation`, `Input-Edit` and ~Information~ `Context Modals`.

- All Modals have had structural changes so they are now RTL-LTR friendly – no more centred text
- Confirmation Modals now have two visual options to choose from: Default (no spot animation) & Prominent (yes spot animation)
- Roadblock Modal is now just a regular old `Confirmation Modal` using the new `Assertive Mood` ([more info on the new moods](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/?node-id=1929%3A81))
- Information Modals are now called Context Modals

[UI Kit: Heart - Modal sticker sheet](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/?node-id=1929%3A35439)

Happy to pair with an Engineer 🥑 , just let me know!

## Work breakdown

- [x] Break the work up into parts
- [x] InputModal [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2300)
- [x] ConfirmationModal (variants: default, prominent) [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2308/)
- [x] ContextModal (variants: portrait, landscape) [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2323)
- [x] Update Storybook stories into 3 main sheets

### PR DESCRIPTION
**Pull request by NatalieLoyzaga**
# Objective
Update generic modal components and update Input-edit modal to match latest design.
Created new Input Edit Modal story which is controllable.

Notes:
- Ignore previous modal stories! Review only the Input Edit modal sub category in modal [here](https://dev.cultureamp.design/nat/generic-and-input-modal-update/storybook/?path=/story/components-modal-input-edit-modal--input-edit-modals) 
- Created custom breakpoint for smaller mobile phones to be used for the Heading styling as Responsive Typography is still under construction. Will need to come back once Responsive Typography is complete to remove custom styles.

# Motivation and Context
closes #1469

# Screenshots (if appropriate)
image
image

### CODE REVIEW

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx [hunk 1]
```diff
@@ -64,24 +64,34 @@ const InputEditModal = ({
...
+        <ModalHeader onDismiss={onDismiss}>
+          <div
+            className={classnames(styles.header, {
+              [styles.textAlignRTL]: localeDirection === "rtl",
+              [styles.padded]: !unpadded,
+            })}
+          >
             <ModalAccessibleLabel>
-              <Text tag="h1" style="zen-heading-3" inline>
+              <Heading tag="h2" variant="heading-2">
```
Comment (ActuallyACat) [inline draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:75]: Really glad to see the Zen reference / deprecated component usage gone 👏🏻

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx [hunk 2]
```diff
@@ -64,24 +64,34 @@ const InputEditModal = ({
...
+            dir={localeDirection}
+          >
             {children}
           </div>
         </ModalBody>
         <ModalFooter
           actions={footerActions}
           appearance={type === "negative" ? "destructive" : "primary"}
           automationId={automationId}
+          variant={"input"}
```
Comment (ActuallyACat) [inline draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:93]: /nit You don't need the curly brackets here
```suggestion
          variant="input"
```

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx [hunk 3]
```diff
@@ -4,7 +4,7 @@ import * as React from "react"
 import GenericModalSection from "./GenericModalSection"
 import styles from "./ModalFooter.scss"
 
-type ActionsVarianProps = "information"
+type ActionsVarianProps = "information" | "input"
```
Comment (ActuallyACat) [inline draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx:7]: Since you're in the area, and I know you didn't name this... But can you rename this variable? 
```suggestion
type ActionsVariantProps = "information" | "input"
```

Comment (ActuallyACat) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx:7]: (incl. The usage of this type on line 17)

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss [hunk 4]
```diff
@@ -1,29 +1,41 @@
...
+  @include ca-media-mobile {
+    padding: $ca-grid;
+    flex-direction: column;
+  }
+}
+.actionButton {
+  @include ca-media-mobile {
+    width: 100%;
+    > *,
+    > * > * {
```
Comment (ActuallyACat) [inline draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss:28]: I might be missing something here, but do you need _both_ of these selectors?

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx (hunk 3 above)
Comment (ActuallyACat) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.tsx:7]: Another small nit/ I think this would make more sense to be called "inputEdit" so that it's consistent with the Modal name

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss [hunk 5]
```diff
@@ -11,13 +12,24 @@
...
-  border-bottom: 1px solid $ca-border-color;
+  text-align: left;
+  &.textAlignRTL {
+    text-align: right;
+  }
+  &.padded {
+    padding: $ca-grid $ca-grid * 1.5;
+    @include ca-media-mobile {
+      padding: $ca-grid;
+    }
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss:23]: Nit/one for @ActuallyACat: are we strict on/not leaving a new line before the next declaration?

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx [hunk 6]
```diff
@@ -40,6 +39,7 @@ const InputEditModal = ({
   submitWorking,
   automationId,
   children,
+  unpadded = false,
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:42]: If the default is to be padded, I'd probably prefer this is to be `padded` to save the double-negative here. Unless you're working off of alternative advice already though!

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss (hunk 5 above)
Comment (ActuallyACat) [reply draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.scss:23]: Not really. Out of habit, I add a newline but it's not a codified standard. If it's something we feel strongly about we can create a Stylelint rule.

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx [hunk 7]
```diff
@@ -64,24 +64,34 @@ const InputEditModal = ({
       automationId={automationId}
     >
       <div className={styles.modal} dir={localeDirection}>
-        <ModalHeader unpadded onDismiss={onDismiss}>
-          <div className={styles.header}>
+        <ModalHeader onDismiss={onDismiss}>
+          <div
+            className={classnames(styles.header, {
+              [styles.textAlignRTL]: localeDirection === "rtl",
+              [styles.padded]: !unpadded,
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:71]: As above, this would probably read nicer with 
```
[styles.padded]: padded,
```

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.scss [hunk 8]
```diff
@@ -0,0 +1,4 @@
+.modalDescription {
+  grid-column-start: 2;
+  padding-bottom: 1.5rem;
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleDescription.scss:3]: Can we use a spacing var here?

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss [hunk 9]
```diff
@@ -1,7 +1,27 @@
...
   position: relative;
+  h2 {
+    @include ca-media-mobile {
+      font-size: 1.625rem;
+      line-height: 32px;
+    }
+    @include ca-media-small-mobile {
+      font-size: 1.5rem;
+      line-height: 30px;
+    }
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss:23]: These seem very specific. Are they from Figma? Could we potentially use any other already in use vars?

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx [hunk 10]
```diff
@@ -11,7 +12,11 @@ type ModalAccessibleLabel = React.FunctionComponent<ModalAccessibleLabelProps>
 const ModalAccessibleLabel: ModalAccessibleLabel = ({ children }) => (
   <ModalAccessibleContext.Consumer>
     {({ labelledByID }) => (
-      <div id={labelledByID} tabIndex={-1} className={styles.label}>
+      <div
+        id={labelledByID}
+        tabIndex={-1}
+        className={classnames(styles.modalLabel, {})}
```
Comment (lloydstubber) [inline draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx:18]: Why the empty object?

**Comment by lloydstubber** [comment]
Screen Shot 2021-11-22 at 4 25 36 pm

There should be padding on the second text block so there's always a minimum amount of space between the last sentence and the input like below. I'm guessing there's some global styles saying when there's a second paragraph, don't give it padding. In this case though we do want that padding.
Screen Shot 2021-11-22 at 4 27 32 pm

**Comment by lloydstubber** [comment]
Sidenote: Maybe we shouldn't be rendering that text twice to begin with? Just realised it's the same copy.

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx (hunk 6 above)
Comment (NatalieLoyzaga) [reply draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:42]: @lloydstubber  Yep makes sense! I think my thought was when using each of the components the consumer will now have to add `padded` as a prop to ensure its padded. whereas they would only need to add the prop if they specifically want it unpadded. 

I wonder... Do we need an unpadded / padded prop? This was something that was exisiting already in the components which I continued with these updates.

Comment (lloydstubber) [reply draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:42]: Ahh okay that does make sense then if it's optional and hardly used. I was going more on the readability but what you have makes sense/seems to be what is dotted around the Modal component already. Nice one 👍

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss (hunk 9 above)
Comment (NatalieLoyzaga) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.scss:23]: These were for styling the Headings responsively based on the Figma styles. Eventually they will be removed and replaced with the inherit responsive styles once that separate component is built out. 

I'll update to use vars if there are ones.

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx (hunk 7 above)
Comment (lloydstubber) [reply draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:71]: Disregard as mentioned above

**Comment by NatalieLoyzaga** [comment]
That first modal example is the old story which the structuring of the content within that specific story is weird. I'll double check on the new story when there are two lines of text. But yeah ignore that first story example.

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss (hunk 4 above)
Comment (NatalieLoyzaga) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss:28]: Great question - I will double check what my brain was trying to achieve here

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx (hunk 10 above)
Comment (NatalieLoyzaga) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalAccessibleLabel.tsx:18]: There will be something in that object in the next PR that is Confirmation Modal related so when refactoring I just removed the insides so that this PR is just Input Edit stuff so Yes shouldn't be there but I guess ignore for now :)

File: draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss (hunk 4 above)
Comment (NatalieLoyzaga) [reply draft-packages/modal/KaizenDraft/Modal/Primitives/ModalFooter.scss]: Removed this styling for the button width and used `useMediaQueries` to enable the fullwidth prop for the button component

File: draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx (hunk 6 above)
Comment (dougmacknz) [reply draft-packages/modal/KaizenDraft/Modal/Presets/InputEditModal.tsx:42]: I recently had to create a prop like this and @ActuallyACat and I opted for the name `noPadding`. Soz can we please change this for consistency?

File: draft-packages/modal/KaizenDraft/Modal/Presets/matchMedia.mock [hunk 11]
```diff
@@ -0,0 +1,15 @@
+// Must be imported before the tested file
```
Comment (ActuallyACat) [inline draft-packages/modal/KaizenDraft/Modal/Presets/matchMedia.mock:1]: I wonder if this should be a global mock given it's used in every package (that has tests) that uses Illustrations. 🤔

**Comment by ActuallyACat** [comment]
Couldn't help myself and unblocked Chromatic. Double checking that this change was intentional (CTA buttons swapped on information modal)? https://www.chromatic.com/test?appId=5e12c297b9d9020020789ca3&id=619c6ed091af89003a30d7a0

**Comment by NatalieLoyzaga** [comment]
@ActuallyACat I can't open that chromatic link / how do I find it in chromatic otherwise? - But I would say it would be intentional as Information modal using the generic Modal footer component and is getting a design revamp which will be complete in the later PRs. Although without me seeing the actual diff I can't be 100%.

**Comment by ActuallyACat** [comment]
I'll add you to the project 😅 This was the screengrab: 
Screen Shot 2021-11-23 at 3 55 05 pm

If it's being fixed in a subsequent PR I'll approve

**Comment by NatalieLoyzaga** [comment]
@ActuallyACat Thanks! Yep its correct/intentional. The image and content positions will swap in the later updates.

**Review by ActuallyACat — APPROVED** [review]
